// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentTeacher.proto

package com.wxsk.protobuf;

public final class StudentTeacher {
  private StudentTeacher() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Sex}
   */
  public enum Sex
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Female = 0;</code>
     */
    Female(0),
    /**
     * <code>Male = 1;</code>
     */
    Male(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Female = 0;</code>
     */
    public static final int Female_VALUE = 0;
    /**
     * <code>Male = 1;</code>
     */
    public static final int Male_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Sex valueOf(int value) {
      return forNumber(value);
    }

    public static Sex forNumber(int value) {
      switch (value) {
        case 0: return Female;
        case 1: return Male;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sex>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sex> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
            public Sex findValueByNumber(int number) {
              return Sex.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wxsk.protobuf.StudentTeacher.getDescriptor().getEnumTypes().get(0);
    }

    private static final Sex[] VALUES = values();

    public static Sex valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Sex(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Sex)
  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .Sex sex = 3;</code>
     */
    int getSexValue();
    /**
     * <code>optional .Sex sex = 3;</code>
     */
    com.wxsk.protobuf.StudentTeacher.Sex getSex();

    /**
     * <code>optional int64 birthday = 4;</code>
     */
    long getBirthday();

    /**
     * <code>optional .Teacher teacher = 5;</code>
     */
    boolean hasTeacher();
    /**
     * <code>optional .Teacher teacher = 5;</code>
     */
    com.wxsk.protobuf.StudentTeacher.Teacher getTeacher();
    /**
     * <code>optional .Teacher teacher = 5;</code>
     */
    com.wxsk.protobuf.StudentTeacher.TeacherOrBuilder getTeacherOrBuilder();
  }
  /**
   * Protobuf type {@code Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      id_ = 0L;
      name_ = "";
      sex_ = 0;
      birthday_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              sex_ = rawValue;
              break;
            }
            case 32: {

              birthday_ = input.readInt64();
              break;
            }
            case 42: {
              com.wxsk.protobuf.StudentTeacher.Teacher.Builder subBuilder = null;
              if (teacher_ != null) {
                subBuilder = teacher_.toBuilder();
              }
              teacher_ = input.readMessage(com.wxsk.protobuf.StudentTeacher.Teacher.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(teacher_);
                teacher_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wxsk.protobuf.StudentTeacher.internal_static_Student_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wxsk.protobuf.StudentTeacher.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wxsk.protobuf.StudentTeacher.Student.class, com.wxsk.protobuf.StudentTeacher.Student.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>optional .Sex sex = 3;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <code>optional .Sex sex = 3;</code>
     */
    public com.wxsk.protobuf.StudentTeacher.Sex getSex() {
      com.wxsk.protobuf.StudentTeacher.Sex result = com.wxsk.protobuf.StudentTeacher.Sex.valueOf(sex_);
      return result == null ? com.wxsk.protobuf.StudentTeacher.Sex.UNRECOGNIZED : result;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 4;
    private long birthday_;
    /**
     * <code>optional int64 birthday = 4;</code>
     */
    public long getBirthday() {
      return birthday_;
    }

    public static final int TEACHER_FIELD_NUMBER = 5;
    private com.wxsk.protobuf.StudentTeacher.Teacher teacher_;
    /**
     * <code>optional .Teacher teacher = 5;</code>
     */
    public boolean hasTeacher() {
      return teacher_ != null;
    }
    /**
     * <code>optional .Teacher teacher = 5;</code>
     */
    public com.wxsk.protobuf.StudentTeacher.Teacher getTeacher() {
      return teacher_ == null ? com.wxsk.protobuf.StudentTeacher.Teacher.getDefaultInstance() : teacher_;
    }
    /**
     * <code>optional .Teacher teacher = 5;</code>
     */
    public com.wxsk.protobuf.StudentTeacher.TeacherOrBuilder getTeacherOrBuilder() {
      return getTeacher();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (sex_ != com.wxsk.protobuf.StudentTeacher.Sex.Female.getNumber()) {
        output.writeEnum(3, sex_);
      }
      if (birthday_ != 0L) {
        output.writeInt64(4, birthday_);
      }
      if (teacher_ != null) {
        output.writeMessage(5, getTeacher());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (sex_ != com.wxsk.protobuf.StudentTeacher.Sex.Female.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, sex_);
      }
      if (birthday_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, birthday_);
      }
      if (teacher_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTeacher());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wxsk.protobuf.StudentTeacher.Student)) {
        return super.equals(obj);
      }
      com.wxsk.protobuf.StudentTeacher.Student other = (com.wxsk.protobuf.StudentTeacher.Student) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && sex_ == other.sex_;
      result = result && (getBirthday()
          == other.getBirthday());
      result = result && (hasTeacher() == other.hasTeacher());
      if (hasTeacher()) {
        result = result && getTeacher()
            .equals(other.getTeacher());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBirthday());
      if (hasTeacher()) {
        hash = (37 * hash) + TEACHER_FIELD_NUMBER;
        hash = (53 * hash) + getTeacher().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wxsk.protobuf.StudentTeacher.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wxsk.protobuf.StudentTeacher.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wxsk.protobuf.StudentTeacher.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        com.wxsk.protobuf.StudentTeacher.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wxsk.protobuf.StudentTeacher.internal_static_Student_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wxsk.protobuf.StudentTeacher.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wxsk.protobuf.StudentTeacher.Student.class, com.wxsk.protobuf.StudentTeacher.Student.Builder.class);
      }

      // Construct using com.wxsk.protobuf.StudentTeacher.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        sex_ = 0;

        birthday_ = 0L;

        if (teacherBuilder_ == null) {
          teacher_ = null;
        } else {
          teacher_ = null;
          teacherBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wxsk.protobuf.StudentTeacher.internal_static_Student_descriptor;
      }

      public com.wxsk.protobuf.StudentTeacher.Student getDefaultInstanceForType() {
        return com.wxsk.protobuf.StudentTeacher.Student.getDefaultInstance();
      }

      public com.wxsk.protobuf.StudentTeacher.Student build() {
        com.wxsk.protobuf.StudentTeacher.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wxsk.protobuf.StudentTeacher.Student buildPartial() {
        com.wxsk.protobuf.StudentTeacher.Student result = new com.wxsk.protobuf.StudentTeacher.Student(this);
        result.id_ = id_;
        result.name_ = name_;
        result.sex_ = sex_;
        result.birthday_ = birthday_;
        if (teacherBuilder_ == null) {
          result.teacher_ = teacher_;
        } else {
          result.teacher_ = teacherBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wxsk.protobuf.StudentTeacher.Student) {
          return mergeFrom((com.wxsk.protobuf.StudentTeacher.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wxsk.protobuf.StudentTeacher.Student other) {
        if (other == com.wxsk.protobuf.StudentTeacher.Student.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        if (other.getBirthday() != 0L) {
          setBirthday(other.getBirthday());
        }
        if (other.hasTeacher()) {
          mergeTeacher(other.getTeacher());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wxsk.protobuf.StudentTeacher.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wxsk.protobuf.StudentTeacher.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ = 0;
      /**
       * <code>optional .Sex sex = 3;</code>
       */
      public int getSexValue() {
        return sex_;
      }
      /**
       * <code>optional .Sex sex = 3;</code>
       */
      public Builder setSexValue(int value) {
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Sex sex = 3;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.Sex getSex() {
        com.wxsk.protobuf.StudentTeacher.Sex result = com.wxsk.protobuf.StudentTeacher.Sex.valueOf(sex_);
        return result == null ? com.wxsk.protobuf.StudentTeacher.Sex.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .Sex sex = 3;</code>
       */
      public Builder setSex(com.wxsk.protobuf.StudentTeacher.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Sex sex = 3;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private long birthday_ ;
      /**
       * <code>optional int64 birthday = 4;</code>
       */
      public long getBirthday() {
        return birthday_;
      }
      /**
       * <code>optional int64 birthday = 4;</code>
       */
      public Builder setBirthday(long value) {
        
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 birthday = 4;</code>
       */
      public Builder clearBirthday() {
        
        birthday_ = 0L;
        onChanged();
        return this;
      }

      private com.wxsk.protobuf.StudentTeacher.Teacher teacher_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wxsk.protobuf.StudentTeacher.Teacher, com.wxsk.protobuf.StudentTeacher.Teacher.Builder, com.wxsk.protobuf.StudentTeacher.TeacherOrBuilder> teacherBuilder_;
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      public boolean hasTeacher() {
        return teacherBuilder_ != null || teacher_ != null;
      }
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.Teacher getTeacher() {
        if (teacherBuilder_ == null) {
          return teacher_ == null ? com.wxsk.protobuf.StudentTeacher.Teacher.getDefaultInstance() : teacher_;
        } else {
          return teacherBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      public Builder setTeacher(com.wxsk.protobuf.StudentTeacher.Teacher value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          teacher_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      public Builder setTeacher(
          com.wxsk.protobuf.StudentTeacher.Teacher.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          teacher_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      public Builder mergeTeacher(com.wxsk.protobuf.StudentTeacher.Teacher value) {
        if (teacherBuilder_ == null) {
          if (teacher_ != null) {
            teacher_ =
              com.wxsk.protobuf.StudentTeacher.Teacher.newBuilder(teacher_).mergeFrom(value).buildPartial();
          } else {
            teacher_ = value;
          }
          onChanged();
        } else {
          teacherBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          teacher_ = null;
          onChanged();
        } else {
          teacher_ = null;
          teacherBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.Teacher.Builder getTeacherBuilder() {
        
        onChanged();
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.TeacherOrBuilder getTeacherOrBuilder() {
        if (teacherBuilder_ != null) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          return teacher_ == null ?
              com.wxsk.protobuf.StudentTeacher.Teacher.getDefaultInstance() : teacher_;
        }
      }
      /**
       * <code>optional .Teacher teacher = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wxsk.protobuf.StudentTeacher.Teacher, com.wxsk.protobuf.StudentTeacher.Teacher.Builder, com.wxsk.protobuf.StudentTeacher.TeacherOrBuilder> 
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wxsk.protobuf.StudentTeacher.Teacher, com.wxsk.protobuf.StudentTeacher.Teacher.Builder, com.wxsk.protobuf.StudentTeacher.TeacherOrBuilder>(
                  getTeacher(),
                  getParentForChildren(),
                  isClean());
          teacher_ = null;
        }
        return teacherBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final com.wxsk.protobuf.StudentTeacher.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wxsk.protobuf.StudentTeacher.Student();
    }

    public static com.wxsk.protobuf.StudentTeacher.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    public com.wxsk.protobuf.StudentTeacher.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int64 birthday = 3;</code>
     */
    long getBirthday();

    /**
     * <code>optional .Sex sex = 4;</code>
     */
    int getSexValue();
    /**
     * <code>optional .Sex sex = 4;</code>
     */
    com.wxsk.protobuf.StudentTeacher.Sex getSex();

    /**
     * <code>repeated .Student student = 5;</code>
     */
    java.util.List<com.wxsk.protobuf.StudentTeacher.Student> 
        getStudentList();
    /**
     * <code>repeated .Student student = 5;</code>
     */
    com.wxsk.protobuf.StudentTeacher.Student getStudent(int index);
    /**
     * <code>repeated .Student student = 5;</code>
     */
    int getStudentCount();
    /**
     * <code>repeated .Student student = 5;</code>
     */
    java.util.List<? extends com.wxsk.protobuf.StudentTeacher.StudentOrBuilder> 
        getStudentOrBuilderList();
    /**
     * <code>repeated .Student student = 5;</code>
     */
    com.wxsk.protobuf.StudentTeacher.StudentOrBuilder getStudentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Teacher}
   */
  public  static final class Teacher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Teacher)
      TeacherOrBuilder {
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      id_ = 0L;
      name_ = "";
      birthday_ = 0L;
      sex_ = 0;
      student_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              birthday_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              sex_ = rawValue;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                student_ = new java.util.ArrayList<com.wxsk.protobuf.StudentTeacher.Student>();
                mutable_bitField0_ |= 0x00000010;
              }
              student_.add(
                  input.readMessage(com.wxsk.protobuf.StudentTeacher.Student.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          student_ = java.util.Collections.unmodifiableList(student_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wxsk.protobuf.StudentTeacher.internal_static_Teacher_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wxsk.protobuf.StudentTeacher.internal_static_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wxsk.protobuf.StudentTeacher.Teacher.class, com.wxsk.protobuf.StudentTeacher.Teacher.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 3;
    private long birthday_;
    /**
     * <code>optional int64 birthday = 3;</code>
     */
    public long getBirthday() {
      return birthday_;
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>optional .Sex sex = 4;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <code>optional .Sex sex = 4;</code>
     */
    public com.wxsk.protobuf.StudentTeacher.Sex getSex() {
      com.wxsk.protobuf.StudentTeacher.Sex result = com.wxsk.protobuf.StudentTeacher.Sex.valueOf(sex_);
      return result == null ? com.wxsk.protobuf.StudentTeacher.Sex.UNRECOGNIZED : result;
    }

    public static final int STUDENT_FIELD_NUMBER = 5;
    private java.util.List<com.wxsk.protobuf.StudentTeacher.Student> student_;
    /**
     * <code>repeated .Student student = 5;</code>
     */
    public java.util.List<com.wxsk.protobuf.StudentTeacher.Student> getStudentList() {
      return student_;
    }
    /**
     * <code>repeated .Student student = 5;</code>
     */
    public java.util.List<? extends com.wxsk.protobuf.StudentTeacher.StudentOrBuilder> 
        getStudentOrBuilderList() {
      return student_;
    }
    /**
     * <code>repeated .Student student = 5;</code>
     */
    public int getStudentCount() {
      return student_.size();
    }
    /**
     * <code>repeated .Student student = 5;</code>
     */
    public com.wxsk.protobuf.StudentTeacher.Student getStudent(int index) {
      return student_.get(index);
    }
    /**
     * <code>repeated .Student student = 5;</code>
     */
    public com.wxsk.protobuf.StudentTeacher.StudentOrBuilder getStudentOrBuilder(
        int index) {
      return student_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (birthday_ != 0L) {
        output.writeInt64(3, birthday_);
      }
      if (sex_ != com.wxsk.protobuf.StudentTeacher.Sex.Female.getNumber()) {
        output.writeEnum(4, sex_);
      }
      for (int i = 0; i < student_.size(); i++) {
        output.writeMessage(5, student_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (birthday_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, birthday_);
      }
      if (sex_ != com.wxsk.protobuf.StudentTeacher.Sex.Female.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, sex_);
      }
      for (int i = 0; i < student_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, student_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wxsk.protobuf.StudentTeacher.Teacher)) {
        return super.equals(obj);
      }
      com.wxsk.protobuf.StudentTeacher.Teacher other = (com.wxsk.protobuf.StudentTeacher.Teacher) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getBirthday()
          == other.getBirthday());
      result = result && sex_ == other.sex_;
      result = result && getStudentList()
          .equals(other.getStudentList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBirthday());
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      if (getStudentCount() > 0) {
        hash = (37 * hash) + STUDENT_FIELD_NUMBER;
        hash = (53 * hash) + getStudentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wxsk.protobuf.StudentTeacher.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wxsk.protobuf.StudentTeacher.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wxsk.protobuf.StudentTeacher.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Teacher)
        com.wxsk.protobuf.StudentTeacher.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wxsk.protobuf.StudentTeacher.internal_static_Teacher_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wxsk.protobuf.StudentTeacher.internal_static_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wxsk.protobuf.StudentTeacher.Teacher.class, com.wxsk.protobuf.StudentTeacher.Teacher.Builder.class);
      }

      // Construct using com.wxsk.protobuf.StudentTeacher.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStudentFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        birthday_ = 0L;

        sex_ = 0;

        if (studentBuilder_ == null) {
          student_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          studentBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wxsk.protobuf.StudentTeacher.internal_static_Teacher_descriptor;
      }

      public com.wxsk.protobuf.StudentTeacher.Teacher getDefaultInstanceForType() {
        return com.wxsk.protobuf.StudentTeacher.Teacher.getDefaultInstance();
      }

      public com.wxsk.protobuf.StudentTeacher.Teacher build() {
        com.wxsk.protobuf.StudentTeacher.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wxsk.protobuf.StudentTeacher.Teacher buildPartial() {
        com.wxsk.protobuf.StudentTeacher.Teacher result = new com.wxsk.protobuf.StudentTeacher.Teacher(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.birthday_ = birthday_;
        result.sex_ = sex_;
        if (studentBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            student_ = java.util.Collections.unmodifiableList(student_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.student_ = student_;
        } else {
          result.student_ = studentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wxsk.protobuf.StudentTeacher.Teacher) {
          return mergeFrom((com.wxsk.protobuf.StudentTeacher.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wxsk.protobuf.StudentTeacher.Teacher other) {
        if (other == com.wxsk.protobuf.StudentTeacher.Teacher.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getBirthday() != 0L) {
          setBirthday(other.getBirthday());
        }
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        if (studentBuilder_ == null) {
          if (!other.student_.isEmpty()) {
            if (student_.isEmpty()) {
              student_ = other.student_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureStudentIsMutable();
              student_.addAll(other.student_);
            }
            onChanged();
          }
        } else {
          if (!other.student_.isEmpty()) {
            if (studentBuilder_.isEmpty()) {
              studentBuilder_.dispose();
              studentBuilder_ = null;
              student_ = other.student_;
              bitField0_ = (bitField0_ & ~0x00000010);
              studentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStudentFieldBuilder() : null;
            } else {
              studentBuilder_.addAllMessages(other.student_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wxsk.protobuf.StudentTeacher.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wxsk.protobuf.StudentTeacher.Teacher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long birthday_ ;
      /**
       * <code>optional int64 birthday = 3;</code>
       */
      public long getBirthday() {
        return birthday_;
      }
      /**
       * <code>optional int64 birthday = 3;</code>
       */
      public Builder setBirthday(long value) {
        
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 birthday = 3;</code>
       */
      public Builder clearBirthday() {
        
        birthday_ = 0L;
        onChanged();
        return this;
      }

      private int sex_ = 0;
      /**
       * <code>optional .Sex sex = 4;</code>
       */
      public int getSexValue() {
        return sex_;
      }
      /**
       * <code>optional .Sex sex = 4;</code>
       */
      public Builder setSexValue(int value) {
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Sex sex = 4;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.Sex getSex() {
        com.wxsk.protobuf.StudentTeacher.Sex result = com.wxsk.protobuf.StudentTeacher.Sex.valueOf(sex_);
        return result == null ? com.wxsk.protobuf.StudentTeacher.Sex.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .Sex sex = 4;</code>
       */
      public Builder setSex(com.wxsk.protobuf.StudentTeacher.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Sex sex = 4;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.wxsk.protobuf.StudentTeacher.Student> student_ =
        java.util.Collections.emptyList();
      private void ensureStudentIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          student_ = new java.util.ArrayList<com.wxsk.protobuf.StudentTeacher.Student>(student_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.wxsk.protobuf.StudentTeacher.Student, com.wxsk.protobuf.StudentTeacher.Student.Builder, com.wxsk.protobuf.StudentTeacher.StudentOrBuilder> studentBuilder_;

      /**
       * <code>repeated .Student student = 5;</code>
       */
      public java.util.List<com.wxsk.protobuf.StudentTeacher.Student> getStudentList() {
        if (studentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(student_);
        } else {
          return studentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public int getStudentCount() {
        if (studentBuilder_ == null) {
          return student_.size();
        } else {
          return studentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.Student getStudent(int index) {
        if (studentBuilder_ == null) {
          return student_.get(index);
        } else {
          return studentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder setStudent(
          int index, com.wxsk.protobuf.StudentTeacher.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.set(index, value);
          onChanged();
        } else {
          studentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder setStudent(
          int index, com.wxsk.protobuf.StudentTeacher.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder addStudent(com.wxsk.protobuf.StudentTeacher.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.add(value);
          onChanged();
        } else {
          studentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder addStudent(
          int index, com.wxsk.protobuf.StudentTeacher.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentIsMutable();
          student_.add(index, value);
          onChanged();
        } else {
          studentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder addStudent(
          com.wxsk.protobuf.StudentTeacher.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.add(builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder addStudent(
          int index, com.wxsk.protobuf.StudentTeacher.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder addAllStudent(
          java.lang.Iterable<? extends com.wxsk.protobuf.StudentTeacher.Student> values) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, student_);
          onChanged();
        } else {
          studentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          student_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public Builder removeStudent(int index) {
        if (studentBuilder_ == null) {
          ensureStudentIsMutable();
          student_.remove(index);
          onChanged();
        } else {
          studentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.Student.Builder getStudentBuilder(
          int index) {
        return getStudentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.StudentOrBuilder getStudentOrBuilder(
          int index) {
        if (studentBuilder_ == null) {
          return student_.get(index);  } else {
          return studentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public java.util.List<? extends com.wxsk.protobuf.StudentTeacher.StudentOrBuilder> 
           getStudentOrBuilderList() {
        if (studentBuilder_ != null) {
          return studentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(student_);
        }
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.Student.Builder addStudentBuilder() {
        return getStudentFieldBuilder().addBuilder(
            com.wxsk.protobuf.StudentTeacher.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public com.wxsk.protobuf.StudentTeacher.Student.Builder addStudentBuilder(
          int index) {
        return getStudentFieldBuilder().addBuilder(
            index, com.wxsk.protobuf.StudentTeacher.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .Student student = 5;</code>
       */
      public java.util.List<com.wxsk.protobuf.StudentTeacher.Student.Builder> 
           getStudentBuilderList() {
        return getStudentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.wxsk.protobuf.StudentTeacher.Student, com.wxsk.protobuf.StudentTeacher.Student.Builder, com.wxsk.protobuf.StudentTeacher.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.wxsk.protobuf.StudentTeacher.Student, com.wxsk.protobuf.StudentTeacher.Student.Builder, com.wxsk.protobuf.StudentTeacher.StudentOrBuilder>(
                  student_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          student_ = null;
        }
        return studentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Teacher)
    }

    // @@protoc_insertion_point(class_scope:Teacher)
    private static final com.wxsk.protobuf.StudentTeacher.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wxsk.protobuf.StudentTeacher.Teacher();
    }

    public static com.wxsk.protobuf.StudentTeacher.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Teacher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    public com.wxsk.protobuf.StudentTeacher.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Teacher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024StudentTeacher.proto\"c\n\007Student\022\n\n\002id\030" +
      "\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\021\n\003sex\030\003 \001(\0162\004.Sex\022\020" +
      "\n\010birthday\030\004 \001(\003\022\031\n\007teacher\030\005 \001(\0132\010.Teac" +
      "her\"c\n\007Teacher\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t" +
      "\022\020\n\010birthday\030\003 \001(\003\022\021\n\003sex\030\004 \001(\0162\004.Sex\022\031\n" +
      "\007student\030\005 \003(\0132\010.Student*\033\n\003Sex\022\n\n\006Femal" +
      "e\020\000\022\010\n\004Male\020\001B#\n\021com.wxsk.protobufB\016Stud" +
      "entTeacherb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "Sex", "Birthday", "Teacher", });
    internal_static_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Teacher_descriptor,
        new java.lang.String[] { "Id", "Name", "Birthday", "Sex", "Student", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
